//
//  SDKPayECLoyaltyCard.h
//  SDKPayeCom
//
//  Created by Stavny, Peter on 12/08/2019.
//  Copyright © 2023 PagoNxt Merchant Solutions S.L. and Santander España Merchant Services, Entidad de Pago, S.L.U. You may not use this file except in compliance with the License which is available at https://mit-license.org/
//

#import <Foundation/Foundation.h>

/**
 * @brief Loyality Card
 */
@interface SDKPayECLoyaltyCard : NSObject
/**
 * @brief Account number
 */
@property (strong, nonatomic) NSString *accountNumber;
/**
 * @brief Personal Identification Number
 */
@property (strong, nonatomic) NSString *pin;
/**
 * @brief Promotional code associated with the enrollment of the user. VOP sets the PromoCode to upper case upon receipt. Alphanumeric. No special characters. max. 36
 */
@property (strong, nonatomic) NSString *promotionCode;
/**
 * @brief Activity
 */
@property (strong, nonatomic) NSDate *activityDate;
/**
 * @brief This is unique VOP User ID generated by VOP system upon successful enrollment. max. 36
 */
@property (strong, nonatomic) NSString *userID;
/**
 * @brief This is unique VOP Card ID generated by VOP system upon successful enrollment. max. 36
 */
@property (strong, nonatomic) NSString *cardID;
/**
 * @brief Production code
 */
@property (strong, nonatomic) NSString *productCode;

@end
