phrase:
  access_token: c5afe0a944cb83c031311c42e62877a574b7a77bcd06f0dc3d7b61a8cadc3740
  project_id: 0bb2d6bb58739260d06f261c127993fb
  push:
    sources:
    - file: ./<locale_code>.lproj/Localizable.strings
      params:
        file_format: strings
        format_options: { convert_placeholder: true }
  pull:
    targets:
    - file: ./<locale_code>.lproj/Localizable.strings
      params:
        file_format: strings
        format_options: { convert_placeholder: true }