//
//  SDKPayECRatePayElvPayment.h
//  SDKPayeComRatePay
//
//  Created by Marian Polek on 03/10/2022.
//  Copyright © 2023 PagoNxt Merchant Solutions S.L. and Santander España Merchant Services, Entidad de Pago, S.L.U. You may not use this file except in compliance with the License which is available at https://mit-license.org/
//

#import <SDKPayeCom/SDKPayeCom.h>

@interface SDKPayECRatePayElvPayment : SDKPayECPayment

/**
 @brief The Creditor Id.
 @details It is mandatory.
 */
@property (strong, nonatomic, nonnull ) NSString *creditorID;

/**
 @brief The Mandate Id for the Mandate Transaction, generated by merchant.
 */
@property (strong, nonatomic, nonnull ) NSString *mandateID;
/**
 @brief The date that the Mandate was signed.
 @details It is optional. If value is nil, current date will be used.
 */
@property (strong, nonatomic, nullable) NSDate *mandateSignedDate;

/**
 @brief The date that the Mandate Transaction is due
 */
@property (strong, nonatomic, nullable) NSDate *dueDate;

/**
 @brief fingerprint parameter inside device object
 */
@property (strong, nonatomic, nonnull) NSString *fingerprint;

@end
